name: Deploy rabbitMQ to Local minikube cluster 

on: 
  push:
    branches:
      - master

jobs:
  check-files:
    runs-on: "self-hosted"
    steps: 
      - name: checkout the repo
        uses: actions/checkout@v4

      - name: navigate to the directory of the rabbitmq deployment manifests and list directories
        working-directory: src\rabbit\manifests
        run: ls

      
